apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi
        image: registryxgu1560.azurecr.io/hacker3/poi:1.0
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: SQL_PASSWORD
        - name: SQL_SERVER
          value: "sqlserverxgu1560.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: SQL_USER
          value: "sqladminxGu1560"
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  ports:
  - port: 80
  selector:
    app: poi